version: "3.0"

services:
  bookmarkit-ui:
    container_name: bookmarkit
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
